### ISSUE TITLE
CACHING is defined twice

### ISSUE THREAD

**Issue by nitriques** [symphonycms/jit_image_manipulation#101]
I am pretty sure this is a mistake....

https://github.com/symphonycms/jit_image_manipulation/blob/integration/lib/image.php#L28

https://github.com/symphonycms/jit_image_manipulation/blob/integration/lib/image.php#L168

I would remove the second one.

**Comment by michael-e** [comment]
Yep, looks like a mistake.

**Comment by brendo** [comment]
It is a mistake :(

**Comment by nitriques** [comment]
I'll fix this then.
