### ISSUE TITLE
Undefined function after upgrading

### ISSUE THREAD

**Issue by pixelninja** [symphonycms/jit_image_manipulation#102]
Hi,

I had a site set up using JIT on 2.4 which worked fine, but after upgrading Symphony to 2.5.2, and JIT to 1.31, JIT has stopped working.

I have turned on JIT errors (line 3 of lib/image.php) and the message is

`Fatal error: Call to undefined function imagecreatefrompng() in /extensions/jit_image_manipulation/lib/class.image.php on line 113`

I did a find all for that function (incase it was in a file that needed including), and it isn't being defined anywhere. 

Any ideas?

**Comment by pixelninja** [comment]
File type is (transparent) PNG. It is fine with JPGs.

**Comment by brendo** [comment]
[This may be relevant](http://stackoverflow.com/questions/18821162/imagecreatefrompng-is-not-working-at-all). Is GD configured to allow PNG's?

**Comment by bernardodiasc** [comment]
Hey @pixelninja, can you check if the resolution of this issue https://github.com/symphonycms/jit_image_manipulation/issues/94 solves your case?

**Comment by pixelninja** [comment]
Ahh thanks guys. My bad, I should have checked closed issues.

It was related to upgrading OS X to Yosemite. Updating to php 5.6 did the trick.

Sorry! As you were.

**Comment by bernardodiasc** [comment]
No worries, nice that worked for you :)
