### ISSUE TITLE
Semver

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/jit_image_manipulation#104]
It would be nice if this extension followed the example of the core and used semantic versioning.

**Comment by nitriques** [comment]
Totally.

**Comment by brendo** [comment]
Yep, to do so we'd have to bump it to 2.0. Reason being is 1.4.1 < 1.41.

**Comment by nilshoerrmann** [comment]
`1.50.0`?

**Comment by nitriques** [comment]
1.42.0 would be ok for now... I would wait for Sym 3.0.0 to go to 2.0.0.
