### ISSUE TITLE
Thumbnails are pixelated

### ISSUE THREAD

**Issue by nonozone** [symphonycms/jit_image_manipulation#113]
![2015-10-26_14-08-47](https://cloud.githubusercontent.com/assets/1277444/10722421/1d76d6ec-7beb-11e5-9219-0dc8e50fe56c.png)

I do not know where the problem.
the version of JIT is 1.43.

And the directory Manifest/cache  is empty

**Comment by nitriques** [comment]
Can you check your quality settings ? And what the complete url for the image ?

**Comment by nonozone** [comment]
The img  url address:  waysionhd.com/image/2/100/75/5/fff/upload/Products/mopro7-front-562d80e40e692.jpg ,you can change the JIT setting for test.

How to set the quality?

**Comment by nonozone** [comment]
This is very strange. I just visit my website, thumbnail display is problematic. But I just try to modify the parameters of JIT, the image / 2/100/75/5 into image / 2/200/75/5, will not actually pixelated thumbnails, and then I have to go back and modify parameters, also did not problem. From yesterday to today, I have not changed any place, this is too bizarre. Now I do not know where exactly the problem, and how they are resolved.

Thank you very much for your reply

**Comment by nitriques** [comment]
> How to set the quality?

Check manifest/config.php. There's a section regarding jit image. (it's called quality). You can set a value between 10 and 100.
