### ISSUE TITLE
Suggestion: Sharpen images

### ISSUE THREAD

**Issue by mprofitl** [symphonycms/jit_image_manipulation#114]
Resizing images leads to lower sharpness. That's why it would be wonderful to have the option of sharping images automatically after resizing. GD library can do this with imageconvolution: http://php.net/manual/de/function.imageconvolution.php. I have tried to implement the code whoen at the end of this message but I failed.

It would be nice to
* activate sharpening in a recipe
* set a sharpening factor in a recipe

Can somebody help?

    /**
     Sharpens the image
    */
    public function imagesharpen() {
    	$matrix = array(
    		array(-1, -1, -1),
    		array(-1, 16, -1),
    		array(-1, -1, -1),
    	);
    	$divisor = array_sum(array_map('array_sum', $matrix));
    	$offset = 0; 
    	imageconvolution($this->_resource, $matrix, $divisor, $offset);
    	return;
    }

**Comment by nitriques** [comment]
> but I failed.

Do you have any errors message ?

---

I really like this. I'd love to implement it, but now I am more urgent things to do, so I can't promise anything.

I would be more than happy to test and PR you may send.

**Comment by michael-e** [comment]
We should keep in mind that "artificial sharpening" will only increase the subjective quality – if at all – on standard monitors, i.e. for standard resolution. With higher resolution (e.g. delivering images for Retina displays) I do not think that it can be an improvement, because it will merely increase the "artificial character" of an image.

Second point: Responsive design often requires images to be scaled in the browser. However, scaling images which have already been "sharpened" for a certain size can not work well.

So this feature is somehow backwards-oriented (working well, maybe, for fixed image sizes on standard resolution displays), and I wouldn't suggest to implement it.

**Comment by nitriques** [comment]
@michael-e Great point. You seem to know a lot more on that topic then me :)

I'll follow your intuition then.

**Comment by michael-e** [comment]
Well, I learned some stuff from graphics designers when I worked as a print journalist (a long time ago). 

Sharpening an image means adding "(edge) overshoot". In simple words: You fool the human eye by artificially increasing contrasts. Of course you must try to keep the manipulated area as small as possible (so for screen images we talk about "single pixel width" lines). If you are really careful with this, it may indeed increase the subjective sharpness, especially on standard resolution monitors. But you may imagine that such a manipulation (which is based on a precise pixel-per-pixel calculation) can not be scaled well afterwards.

**Comment by nitriques** [comment]
Indeed. Thanks for sharing :)

**Comment by mprofitl** [comment]
Hello everybody, I am surprised and happy my suggested feature lead to such a discussion. Thanks for your thoughts so far.

Re-scaling images after sharpening makes no sense indeed. That's why a sharpen feature in JIT is useless for sites that scale images depending on screen size. The site I want to use sharpening for does scale – but only up to a certain size. Using a sharpen filter I could improve the image quality at least for the desktop site. I agree that responsive design reduces the possibilites to use a sharpen filter.

Following your thoughts, michael-e, I searched for and discovered imageconvolution with javascript. It converts images to a canvas object. I am implementing it on a test site currently. For many images on a page canvas is too slow but for a few it might work.

By the way, it was one of our photographers who suggested to apply an unsharp mask on the website pictures.

**Comment by michael-e** [comment]
> it was one of our photographers who suggested to apply an unsharp mask on the website pictures

No surprise. I once made a website for a photographer who manually (!) sharpened each and every picture on the site, and every one of them looked really great! But this was some years ago, we didn't have hi-res tablets or "Retina" Macs at that time. I am rather sure that today he wouldn't do it like this.

Regarding imageconvolution, I looked at the example on http://www.html5rocks.com/en/tutorials/canvas/imagefilters/. Short story: No matter how you do it I am not convinced that image **sharpening** is any good today (unless we talk about optimized images with fixed widths and standard resolution only).

**Comment by nitriques** [comment]
> No surprise. I once made a website for a photographer who manually (!) sharpened each and every picture on the site,

I had the same. They are crazy.
