### ISSUE TITLE
Fatal error: Call to undefined method General::checkFile()

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/jit_image_manipulation#122]
While trying to update JIT Image Manipulation from version 1.41 to 2.0.1 (`integration`) the following error is thrown:

> Fatal error: Call to undefined method General::checkFile() in /www/htdocs/website/extensions/jit_image_manipulation/lib/class.htaccess.php on line 35

We are using Symphony 2.7.0.beta1. The same error is shown when using JIT 2.0.0.

![bildschirmfoto am 2016-06-07 um 10 25 27](https://cloud.githubusercontent.com/assets/25466/15850789/2ecc5452-2c9a-11e6-8747-81b329e9c193.png)

**Comment by nilshoerrmann** [comment]
Just as a sidenote: the function in question _does exist_ in the given install. It seems like something is not referenced/imported correctly.

**Comment by nitriques** [comment]
Hum, this is pretty weird. Do you have the complete stack trace ?

**Comment by nilshoerrmann** [comment]
Hm, I just tried to install 2.0 again and now it worked. 
Can this issue possibly be related to https://github.com/symphonycms/symphony-2/issues/2600?

**Comment by nitriques** [comment]
I do not think it can... The general class has been there forever... Well, I'm glad it's working!

**Comment by nilshoerrmann** [comment]
One idea: When updating my install, we had 1.41 installed. After the problems with 2.0.1 we "downgraded" to 1.45 which was actually still an upgraded from our initial version.

This and the command suggested in https://github.com/symphonycms/symphony-2/issues/2600 were the only changes in the install except a few template edits.

**Comment by nilshoerrmann** [comment]
I just downgraded to 1.41 and tried to upgrade to 2.0.1 and it still works.
So it must be related to https://github.com/symphonycms/symphony-2/issues/2600.

**Comment by nitriques** [comment]
Hum I'll fiddle with this.

How did you downgrade ?

**Comment by nilshoerrmann** [comment]
I replace the extension with the older version (1.41) and installed it (this did reset the version number in the database). Lucking at the extension driver nothing had to change on the file system. I then uploaded version 2.0.1 again an run the updater again.

**Comment by nitriques** [comment]
Ok thanks, I'll try to replicate

**Comment by nitriques** [comment]
On my local setup, clean 2.7.x symphony, no other extension then JIT.

1. `git checkout 1.41`
1. install
1. `git checkout integration`
1. update

Everything worked. Or am I missing something ?

**Comment by nilshoerrmann** [comment]
No, you're not missing anything. 

I've tried to reset things to the initial state in order to recreate the problem. Either reinstalling version 1.41 and updating to 1.45 fixed the issue or using the command Brendan mentioned in https://github.com/symphonycms/symphony-2/issues/2600 must have fixed the cause of this issue. At least I'm not able to recreate the original error, everything is fine here as well.

**Comment by nitriques** [comment]
AAAWWWEEEESSSOOMMMEE !

**Comment by nitriques** [comment]
BTW, when `2.7.x` will be release, you should not need to run `composer`. I will do it and then commit the results.

**Comment by nilshoerrmann** [comment]
Great, thanks!
