### ISSUE TITLE
readme doesn't contain the latest Apache rewrite rule

### ISSUE THREAD

**Issue by DavidOliver** [symphonycms/jit_image_manipulation#126]
If I understand correctly, the rule has been simplified so as not to include file type extensions. (Is this because JIT now checks image type itself?) The readme doesn't yet contain the simplified rule.

By the way, it's useful to have the rule in the readme as we do for those of us who need to convert the rule to non-Apache rewrites.

**Comment by nitriques** [comment]
>  The readme doesn't yet contain the simplified rule.

This move was made years ago. It never caught my eyes that it did and I integrated a regression doing so (See #75 )

A 2.1.0 update section will be created. Thanks!

**Comment by nitriques** [comment]
Done! @DavidOliver Can you please review ? Thanks!

**Comment by DavidOliver** [comment]
Cool - thanks.
