### ISSUE TITLE
max-age config and header are missing

### ISSUE THREAD

**Issue by DavidOliver** [symphonycms/jit_image_manipulation#127]
The `max_age` key/value are not in the `image` array in config.php.

The `max-age` header is not being sent with image responses, whether or not the `max_age` config is present. The `X-jit-mode` and `X-jit-cache` headers are sent. (By the way, what's the purpose of sending these headers?)

`$parameters['last_modified']` doesn't seem to be set in `sendImageHeaders($parameters)`. I'm testing with local (not external) images.

Installed in Symphony 2.7.x branch.

Is this working in Apache? I'm using Hiawatha.

**Comment by nitriques** [comment]
The `max-age` config has been renamed to `max_age` (see 1f63146f3f34be667f43fb6cc1b87aa59a403b50) and does work using the latest version under Apache. This has been documented in 7a1312848d42ef2779dda0b139eb1a08e8a80ed9

> By the way, what's the purpose of sending these headers

DEBUG on production servers!

> $parameters['last_modified'] doesn't seem to be set in 

You are right. I'll fix this. Thanks!

**Comment by nitriques** [comment]
Should be fixed! Can you confirm ?

**Comment by nitriques** [comment]
BTW, some headers are not being sent when doing OPTIONS or HEAD request.

I'll dig deeper on this.

**Comment by DavidOliver** [comment]
I'm now seeing the max-age header. Thanks!

> DEBUG on production servers!

Isn't it best to avoid leaking software info like this? Could we only send them if a valid developer session exists?

**Comment by nitriques** [comment]
> Could we only send them if a valid developer session exists?

Yup will do. The cookie (for now) is sent for all images requests.

- [ ]  only send them if a valid developer session exists

**Comment by nitriques** [comment]
@DavidOliver All fixed in latest `integration`. Wanna test ? :)

**Comment by DavidOliver** [comment]
`max-age` is still working for me in Hiawatha, and the debug headers are not sent when not logged in. Thanks!
