### ISSUE TITLE
"No JIT filter was found for this request"

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/jit_image_manipulation#129]
Using the `integration` branch, I find this message quite a few times:

> 21 June 2016 09:56 > UNKNOWN: JIT\JITParseParametersException 0 - No JIT filter was found for this request. on line 214 of /www/htdocs/v085298/website/2016/extensions/jit_image_manipulation/lib/class.jit.php

What does this error message mean. Is this an usage problem on the front-end or is something inside the extension broken?

**Comment by brendo** [comment]
My guess is frontend, is means the incoming request wasn't able to be parsed to one of the filters that exist in the project, https://github.com/symphonycms/jit_image_manipulation/tree/integration/filters

**Comment by nilshoerrmann** [comment]
No, I don't. I just found these entries in the logs while investigating other issues. Would be helpful, if the error log could feature this information.

**Comment by nitriques** [comment]
@nilshoerrmann d3efada should help you out. The exception you are having result in asking jit for something that is not valid, which anybody with a browser can do. At least, you'll see more info in the logs.

**Comment by nilshoerrmann** [comment]
Thanks, Nicolas. That will help debugging.

**Comment by nitriques** [comment]
My pleasure!
