### ISSUE TITLE
2.1.0: Wrong file permissions

### ISSUE THREAD

**Issue by nilshoerrmann** [symphonycms/jit_image_manipulation#131]
Using the `integration` branch of this extension, it seems that the cached image files don't respect the `write_mode` settings from the Symphony config.

Example: Even if I set `write_mode` to `0777` the resulting image will be saved with `0644`.

**Comment by nitriques** [comment]
> Even if I set write_mode to 0777

You should try to avoid this ! 😉  

But yeah, it's bug.

**Comment by nitriques** [comment]
@nilshoerrmann it seems like it never did... Or I just can't find where it did. Can you confirm that it's a regression ?

**Comment by nilshoerrmann** [comment]
No, I can't confirm that. 
It's just not working as I expected.

**Comment by nitriques** [comment]
Ok! And what was the permission on the cache folder ?

**Comment by nitriques** [comment]
Is the user running the php script owner of the folder ?

**Comment by nilshoerrmann** [comment]
The folder was set to `0777` and the user and owner were different.

**Comment by nitriques** [comment]
So I guess you apache umask must be 133 or something like it.

I my setups, all folder and file are own by the php process and 644 is what I want ;)

I guess that it's only because we do not use Symphony's writeFile function (we use GD to save image on disk) but a chmod operation could be made.

**Comment by nitriques** [comment]
@nilshoerrmann would you happen to know why the default value for the `General::uploadFile()` method is 0777 ? or maybe @brendo or @michael-e would ?

**Comment by michael-e** [comment]
What do you mean by default value? Is there some default in the code that gets overriden by the Symphony configuration?

**Comment by nilshoerrmann** [comment]
I don't understand the question, sorry.

**Comment by nitriques** [comment]
> What do you mean by default value?

The default value for the parameter in the function. It's never used in the core (we always set a value on the call site).

**Comment by michael-e** [comment]
I just guess it is there because otherwise the process would break (if no param is set when calling it). One might as well throw an exception instead… But is this more useful?

**Comment by nitriques** [comment]
I would just set the default value to 0644, like we did in writeFile...

**Comment by michael-e** [comment]
Default permissions of 0777 are pretty dangerous, generally. So I agree, unless @brendo knows why it was done this way.

**Comment by nitriques** [comment]
> are pretty dangerous,

Indeed!

**Comment by nitriques** [comment]
Since we never had any return from @brendo I `git blame`'d the thing and it was set to 0777 in rev5 (https://github.com/symphonycms/symphony-2/commit/7f90fa0542e9cda6c8f5edc23604b536f7c9efe8)

So I went ahead with changing the default to `0644`.

**Comment by nitriques** [comment]
@nilshoerrmann can you confirm that b5584e0 fixes your problems (i.e. the `write_mode` is properlly set) ? Thanks!

**Comment by nilshoerrmann** [comment]
I'll check that out later today.

**Comment by nitriques** [comment]
Perf, thanks!

**Comment by nilshoerrmann** [comment]
It works as advertised.
Thanks, Nicolas!

**Comment by nitriques** [comment]
Awesome!
