### ISSUE TITLE
Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 29440 bytes)

### ISSUE THREAD

**Issue by wdebusschere** [symphonycms/jit_image_manipulation#133]
Uploading image of 3Mb doesn't work anymore..
php.ini: memory_limit  = 256 (or -1) doesn't fix it

**Comment by nitriques** [comment]
`memory_limit` is for the RAM. It has nothing to do with file uploads.

You need other configs. Make sure post_max_size is always bigger then upload.

```
memory_limit = 32M
upload_max_filesize = 24M
post_max_size = 32M
```

**Comment by nitriques** [comment]
Also, uploads has nothing to with the extension.

If the problem is resizing a 3Mb image, yeah, that has never worked.

**Comment by wdebusschere** [comment]
Is there solution to resizing a 3MB image?

**Comment by nitriques** [comment]
Buy a server with more RAM or use cloudinary. I also run a server with a 256Mb limit and it can't handle resizing image larger than 1.5Mb. The best thing to do is to set maximum sizes using image_upload.

**Comment by wdebusschere** [comment]
Ok, image size is the problem 900kb image with width 7000px also gives the error.

**Comment by michael-e** [comment]
> If the problem is resizing a 3Mb image, yeah, that has never worked.

Are you sure? JIT 1.x works fine for me with much bigger images. The error message in the issue's title suggests that the script tried to allocate more than 134217728 bytes (as mentioned) — that is a 128 MB memory limit, which should not be reached with a 3MB image.

**Comment by michael-e** [comment]
Ok, I guess that it depends on the physical image size in pixels, i.e. not on the file size?

With 16MB RAM, I can successfully process a 6 Megapixel image. Haven't tested with much bigger images though.

**Comment by nitriques** [comment]
> Ok, I guess that it depends on the physical image size in pixels, i.e. not on the file size?

Exactly. All images becomes bitmaps in memory, and we keep the original and the resized version of those bmps in memory. So yeah, a 3Mb image can eat more than 128Mb

> Are you sure? JIT 1.x works fine for me with much bigger images.

Yes. Check http://php.net/manual/en/function.imagecreatetruecolor.php 

> With 16MB RAM, 

it all boils down to `memory_limit` on a 64Gb server, I still set it to 512M to prevent memory exhaustion.

**Comment by michael-e** [comment]
Now I tried a really big image: 39 Megapixels (file size: 16MB).

* `php_value memory_limit 256M` — it works 
* `php_value memory_limit 16M` — it still works
* `php_value memory_limit 8M`— it breaks

**Comment by michael-e** [comment]
How can that be???

**Comment by nitriques** [comment]
Did you turn off the cache before testing ?

**Comment by nitriques** [comment]
- 256M got the cache
- 16M got the cache
- 8M cache could not fit in memory... ?

**Comment by nitriques** [comment]
And what's the destination size ?

**Comment by nitriques** [comment]
Checking the memory needed before doing the operation would also be wise...

**Comment by michael-e** [comment]
> And what's the destination size ?

The destination size in this test was very small, something like 120 Pixels wide.

**Comment by michael-e** [comment]
Unfortuantely I can't test too much on this production system, it's the "big one". (I even took all websites down during the tests by setting the memory size too small, hehe...) I don't have any test/development system at the moment.

**Comment by nitriques** [comment]
> very small, something like 120 Pixels wide.

That helps a lot.

> Unfortuantely I can't test too much on this production system, it's the "big one"

**Comment by michael-e** [comment]
I love to work on the production system!

> I am pretty sure you had a cache

Well, no. The cache gets purged when "something" is saved — which I did. I often break things. But nobody ever complained, because my "dev outages" never last long, which is so much better than elsewhere on the web. :-)

**Comment by nitriques** [comment]
Ahaha!

Well I can't explain it with the fact that your thumbnail is kindof small. Mines are often +600px wide

**Comment by michael-e** [comment]
Nope. I just performed the following extreme test:

* `php_value memory_limit 256M`
* original image: 5410 × 7210 pixels, 16,8 MB
* output size: 15000 x 19991 pixels (approx. 300 Megapixels!), 23,5 MB (JIT quality setting: 90)

It works. :-)

**Comment by michael-e** [comment]
(Admitted: I had to increase the max. execution time.)

**Comment by nitriques** [comment]
Wow this is crazy. Which version of PHP + GD do you run ?

**Comment by michael-e** [comment]
* PHP Version: 5.6.22-0+deb8u1
* "GD headers Version": 2.1.1-dev

**Comment by nitriques** [comment]
Ubuntu ?

**Comment by michael-e** [comment]
Nope, Debian.

**Comment by nitriques** [comment]
Potato-Tomato ;)

**Comment by nitriques** [comment]
But that's interesting considering that I may implement the test the memory available before doing the operation thingy.

**Comment by michael-e** [comment]
Yes. I have no explanation for your issues (resp. my no-issue).

**Comment by nitriques** [comment]
7f98c78 won't solve this problem, but could reduce the lot on the server. Use with caution.
