### ISSUE TITLE
.htaccess exists but is not writeable

### ISSUE THREAD

**Issue by jude86-7** [symphonycms/jit_image_manipulation#135]
I'm trying to update the jit extension from 1.44 to the integration (2.0.2?) branch however when I go to update the extension I get the error 'htaccess exists but is not writeable'.

I've tried the .htaccess file with 664 and 666 permissions with the same owner/group as the other files but nothing seems to work.

does anyone have any ideas where I'm going wrong or come across this before?

many thanks

**Comment by nitriques** [comment]
Is the owner of the file the same user as the user which runs the php executable ?

**Comment by nitriques** [comment]
Ping ? Did you tried 644 ? Some php setups (like suphp and suoshin) are picky about file perms...

**Comment by jude86-7** [comment]
hi sorry, I've been caught up with a deadline the last few days. I've tried 644, 664 and 666 nothing seems to work. The owner is the same as all other files on the domain, which seem to be read/writing okay. I'll try going back to my tech guys on the server to see if there's something amiss on their end, it could be because I'm working in a sub folder on our test server. 

does the extension need any permissions itself? I have these set to 644 and 755.

thanks for your help if I find anything useful I'll post it back here for others

**Comment by nitriques** [comment]
> it could be because I'm working in a sub folder on our test server.

That could be the reason yes.

> does the extension need any permissions itself?

Nope!

>  I have these set to 644 and 755.

This should be perfect, as long as the user running php is the same as the owner of the files/folders.

> thanks for your help if I find anything useful I'll post it back here for others

Thanks for reporting it !

**Comment by nitriques** [comment]
Also make sure that your root (in your case, the subfolder) is writable too.

**Comment by nitriques** [comment]
Nothing new here ? Still was not able to reproduce, even in a subfolder..

**Comment by jude86-7** [comment]
Hi, sorry we moved the site from our test server over onto the live server this last week and the extension updated okay with no errors.

Sorry to have troubled you, thank you for looking into it for me.

**Comment by nitriques** [comment]
> Sorry to have troubled you,

No worries, please re-open the ticket if you encounter it again!
