### ISSUE TITLE
server 500 issue on all but the first image on a page

### ISSUE THREAD

**Issue by pixelninja** [symphonycms/jit_image_manipulation#153]
So I'm not sure if this is a localhost issue or not, as I'm currently still developing the site and haven't put it on a live environment server yet.

On initial page load, all images using JIT show correctly, and continue to do so for a few more page loads. But then all images except the first one on the page can't be found. The response is a 500 error, and when looking at it in Chrome Inspect, it is coming up with a MySQL has gone away error.

I thought it might be a memory issue, so I increased the memory limit but had no effect.

This is using the integration branch of JIT, and the latest master branch of Symphony. And using recipes, not numeric image sources.

I reverted JIT to v1.46 and the issue has resolved.

Any ideas as to the cause, or how I can debug this further?

**Comment by pixelninja** [comment]
Update:

I was getting the same error with Association field, in the backend only the first field would load in sections. Other AJAX attempts returned a 500. After some digging, it turns out I had multiple MySQL processes running! No effing idea how my system managed that, but it's only been post MacOS Sierra update so I might need to do some digging there... simply stopping mysql through the terminal has resolved it.

Disregard my issue please :)

**Comment by pixelninja** [comment]
Although worth mentioning, for anyone that comes across the same issue, is I had to remove MySQL completely from my iMac and reinstall it.

[Here's a good guide](https://coderwall.com/p/os6woq/uninstall-all-those-broken-versions-of-mysql-and-re-install-it-with-brew-on-mac-mavericks) (note I use Homebrew)

**Comment by nitriques** [comment]
Weird!
