### ISSUE TITLE
Direct display recipe returns HTTP 500 on SVG

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/jit_image_manipulation#160]
**Edit:** JIT ext v1.46

As mentioned [here](https://github.com/symphonycms/jit_image_manipulation/issues/117#issuecomment-184430959), SVG cannot be "jitted".

Does a `direct display` recipe still do some "jitting"? I thought it would let images just through.

It throws the following error:

    PHP Fatal error:  Uncaught exception 'Exception' with message 'Unable to retreive image size 
    information for .../komfort-1506846024.svg' in 
    .../extensions/jit_image_manipulation/lib/class.image.php:145
    Stack trace:
    #0 .../extensions/jit_image_manipulation/lib/image.php(333): Image::getMetaInformation('...')
    #1 {main}
    thrown in .../extensions/jit_image_manipulation/lib/class.image.php on line 145, referer: http://...

A workaround for this is to use real image path instead of a jit recipe.

PHP v5.6x

**Comment by nitriques** [comment]
This is normal. SVG is not supported by jit since it is not a binary (pixel) format, it does not need to be jitted.
