### ISSUE TITLE
Backend image previews blocked by 'recipes only' preference

### ISSUE THREAD

**Issue by jurajkapsz** [symphonycms/jit_image_manipulation#41]
Sorry, don't know how to reference the https://github.com/symphonycms/symphony-2/issues/1419 thread

> "Disable dynamic URLs and use named recipes only" preference blocks generation of preview thumbs in Symphony's backend section listing, as it uses JIT dynamic URLs parameters.

**Added:** This topic is to advanced for me to come up with some proper solution (whetever to user some kind of system recipes presets for internal previews or to allow backend to bypass the disabling preference).

Solving it at the JIT's side would mean I guess to spare the need to update all other extensions, on the other hand I am not sure if bypassing such a straightforward disabling preference by doing the opposite way under some condition is a good way.

I guess I can not contribute to this. Also I am not a programmer, but making some slowly steps in that way.

Thank you.

**Comment by nitriques** [comment]
I guess that the preview feature is incompatible with this feature. I'll add a warning.
