### ISSUE TITLE
Support GD library CMYK to RGB rendering

### ISSUE THREAD

**Issue by andrewminton** [symphonycms/jit_image_manipulation#47]
As of GD version 2.0.22 there is simple support for CMYK to RGB conversion on the fly so that older browsers may be able to handle images uploaded with CMYK colourspace.

Is there scope to cater for this in the 3 channel meta check conditional within the extension maybe?

**Comment by nitriques** [comment]
How would you implement it ? Not the version checking, but the RGB conversion ? Happy new year BTW!

**Comment by brendo** [comment]
It happens automatically by GD. I've committed this change on `integration`.

**Comment by andrewminton** [comment]
Nice one @brendo :)

**Comment by nitriques** [comment]
+1 @brendo
