### ISSUE TITLE
PNG loses transparent background

### ISSUE THREAD

**Issue by vlad-ghita** [symphonycms/jit_image_manipulation#59]
I have a link to a JIT mode 1 transparent PNG `/image/1/150/0/0/.../logo.png`. I noticed the PNG loses it's transparency.

I tracked it to [these lines][1] in `/lib/class.imagefilter.php`

    $colour = imagecolorallocatealpha($dst, 0, 0, 0, 127);
    imagefill($dst, 0, 0, $colour);

Is there any particular reason for `filling` the image?

[1]: https://github.com/symphonycms/jit_image_manipulation/blob/master/lib/class.imagefilter.php#L29-L30

**Comment by nilshoerrmann** [comment]
This issue is still present in version 2. It worked in the latest iterations of version 1 though, where transparency stayed intact.

**Comment by nilshoerrmann** [comment]
Sorry, I now cleared the Symphony cache and the issue is gone again.
PNG transparency works as expected.

**Comment by nitriques** [comment]
So the issue is fixed ? :) After 3 years, not bad!

**Comment by nilshoerrmann** [comment]
Oh, hang on. The issue just popped up again. Example here at the page bottom: https://durchgedreht24.de/festival/2015/

![bildschirmfoto am 2016-06-21 um 09 18 49](https://cloud.githubusercontent.com/assets/25466/16221110/3b8be62e-3791-11e6-8894-036e230e69aa.png)

The logo in the lower right corner is the only one without transparent background (it has a white background defined).

**Comment by nilshoerrmann** [comment]
There is an other old issue (#3) describing this problem that was fixed like this 5 years ago – maybe that helps finding the culprit: https://github.com/symphonycms/jit_image_manipulation/commit/a0f38e59704d0f600565d21b5ed73584d3755e3c

**Comment by nitriques** [comment]
The `__fill` function did not changed much. It's pretty much the same.

Also, I've downloaded one of your logos, and it's working on my machine with the latest integration branch, both with and without cache.

Which version of GD are you running ? (Check the `GD_VERSION` constant)

**Comment by nilshoerrmann** [comment]
Checking the GD version was a good idea: It seems as if our hoster changed the server settings and only ImageMagick was installed alongside PHP 5.6. If I downgrade to PHP 5.4, I've got GD `bundled (2.1.0 compatible)`. The problem doesn't change though (all caches cleared, different browsers etc.).

**Comment by nitriques** [comment]
Damn. You're running the latest `integration` ? Still can reproduce.

**Comment by nilshoerrmann** [comment]
I'll check, if we are missing commits, but I think we are using latest Symphony 2.7 and latest `integration` of JIT.

**Comment by nilshoerrmann** [comment]
I updated the extension again and this seems to work now. I'm not really sure why but I'm happy that it does. Thanks for your help, Nicolas!

**Comment by nitriques** [comment]
Great! Please reopen if you encounter it again.
