### ISSUE TITLE
Spaces in filenames

### ISSUE THREAD

**Issue by designermonkey** [symphonycms/jit_image_manipulation#60]
@leon13 has hacked JIT (line 178 `image.php`) to make it work with `+` in the filenames:

	$url = parse_url($_SERVER['REQUEST_URI']);
	$bug_image = str_replace('/image/', '', $url['path']);
	$param = processParams($bug_image, $settings['image']);

This obviously stops the need for passing a `GET` param through to JIT, but still requires the `htaccess` rule.

	RewriteRule ^image\/(.+\.(jpg|gif|jpeg|png|bmp))$ extensions/jit_image_manipulation/lib/image.php?param=$1 [B,L,NC]

could now be:

	RewriteRule ^image\/(.+\.(jpg|gif|jpeg|png|bmp))$ extensions/jit_image_manipulation/lib/image.php [B,L,NC]

`$_GET` in php is translating the `+` to a space and therefore it fails in JIT.

**Comment by nitriques** [comment]
As of today, this is fixed! Yeah!
