### ISSUE TITLE
Feature Request: S3 bucket integration (external cache)

### ISSUE THREAD

**Issue by damienoliver** [symphonycms/jit_image_manipulation#69]
It would be great if when using the JIT & S3 upload extensions together we could store the cached images directly in the S3 bucket instead of the default manifest/cache dir.

**Comment by jensscherbl** [comment]
I think this issue should be closed. It's a task for a cache driver and not specific to images imo.

**Comment by jonmifsud** [comment]
@damienoliver you might also want to follow progress on - https://github.com/jonmifsud/s3_image_upload it's something I'm working on at the moment allowing users to crop images at upload point, and sending cropped image straight away to an S3 bucket.

Storing images in an S3 bucket after cropping would still mean you need to hit your server, then be redirected to an S3 bucket, or the other way round hitting an S3 bucket you fail and go back to your server. I'm trying to generate cropped images on save which is more practical.

**Comment by damienoliver** [comment]
@jonmifsud thanks mate, I'll check it out.

I haven't worked on this project for a while, but the image crop was dynamic and I could not know the required dimensions beforehand. 

By memory the issue was more to do with the cache for dynamic cropped images was stored local to the server and was a AWS elastic beanstalk setup, so anything not tracked by the hit repo I.e cache files. Would get removed after a new push. I ended up using a different technique to solve the problem.

**Comment by nitriques** [comment]
>  I ended up using a different technique to solve the problem.

So can we close this issue ?
