### ISSUE TITLE
Add support for jCrop cropping mode and ImageCropper extension

### ISSUE THREAD

**Issue by yojeek** [symphonycms/jit_image_manipulation#73]
Some time ago @klaftertief [forked JIT](https://github.com/klaftertief/jit_image_manipulation/tree/jCrop) to implement new cropping mode for his super-useful [ImageCropper extension](http://symphonyextensions.com/extensions/imagecropper/). However, two JIT extensions can't live together in one Symphony install, what leads to possible compatibility problems, and i don't think that @klaftertief  is still actively maintaining his version of JIT.

In order to better support ImageCropper, is it possible to merge in jCrop cropping mode from @klaftertief repo to the upstream?

**upd** seems that @bernardodiasc maintaining [his fork with jCrop included](https://github.com/bernardodiasc/jit_image_manipulation/commits/jcrop) in actual state

**Comment by nitriques** [comment]
Extending will work starting at version `2.0.0`.

Thanks a lot @brendo for this major rewrite. :+1:
